CREATE TABLE IF NOT EXISTS servicio (
  id BIGSERIAL PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT NOT NULL,
  imagen TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cliente (
  id BIGSERIAL PRIMARY KEY,
  imagen TEXT NOT NULL,
  nombre VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS blog (
  id BIGSERIAL PRIMARY KEY,
  imagen TEXT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  autor VARCHAR(150) NOT NULL,
  descripcion TEXT NOT NULL,
  contenido TEXT NOT NULL
);
